Bài 1:

In [1]:
import torch
import torch.nn as nn

In [2]:
data = torch.tensor([1, 2, 3])
data

tensor([1, 2, 3])

In [4]:
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data.float())
output

tensor([0.0900, 0.2447, 0.6652])

In [5]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        x_exp = torch.exp(x)
        total = x_exp.sum(dim=0, keepdim=True,)
        return x_exp/total

my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [ ]:
data = torch.tensor([1, 2, 30000000])
output = my_softmax(data)
output
# nan do số quá lớn

tensor([0., 0., nan])

In [9]:
class StableSoftmax(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        c = torch.max(x, dim=0)
        x_exp = torch.exp(x - c.values)
        total = x_exp.sum(0, keepdims=True)
        return x_exp/total

stable_softmax = StableSoftmax()
output = stable_softmax(data)
output

tensor([0., 0., 1.])